export const ALL_BOOK_REQUESTS = "ALL_BOOK_REQUESTS";

export const ALL_BOOK_SUCCESS = "ALL_BOOK_SUCCESS";

export const ALL_BOOK_FAILURE = "ALL_BOOK_FAILURE";

export const ALL_BOOK_DETAILS_REQUESTS = "ALL_BOOK_DETAILS__REQUESTS";

export const ALL_BOOK_DETAILS_SUCCESS = "ALL_BOOK_DETAILS_SUCCESS";

export const ALL_BOOK_DETAILS_FAILURE = "ALL_BOOK_DETAILS_FAILURE";

export const  CLEAR_ERRORS = " CLEAR_ERRORS"